### PR TITLE
Integration specs for views and fix n+1 problems

### PR DESCRIPTION
**Pull request by Yorsyboy**
### In this Pull Request, I;

- Make sure that the N+1 problem is solved when fetching all posts and their comments for a user.
- Use Capybara to write integration tests for each view in your project.

### CODE REVIEW

**Review by rloterh — CHANGES_REQUESTED** [review]
Hi Tope,
 
 While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
 
 ## Invalid Code Review Request
You have submitted a project, whereby Multiple linter checks are failing on your Pull Request. Kindly ensure that **all** checks are passing.

**Failing linters**
image


 
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
 
 Cheers and Happy coding!👏👏👏
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _Invalid Code Review Request **does not count** into the code reviews limit._

**Review by smunozmo — APPROVED** [review]
Hi @Yorsyboy, 👋 

## Highlights 👏 

- All features are tested correctly, congrats on it! 😎 
- N+1 problem is solved, great! 🎉 
- Great work using the right GitHub Flow.
- Your README looks professional, well done!
- Commits are descriptive, good work.
- Linters are working properly, great job!

Your project is complete!  There is nothing else to say other than... it's time to merge it! 🚀 
Very nice work, congratulations! 🎉 

# APPROVED! 💯  💯  💯 




Cheers and Happy coding! 🤓 

## Optional suggestions

- [OPTIONAL] Your tests are set up correctly, excellent job! However, as you are using Tailwind, it needs to be precompiled before testing, otherwise, you will get an error when you try to run the tests, therefore, I would recommend adding `bundle exec rake assets:precompile` to the 'Testing' section of your README file, this way anyone would know how to do it.

- [OPTIONAL] In the other tests that you have that are not a requirement for this activity, there's an error:

Screen Shot 2022-08-22 at 12 35 31 PM

I see that you have an `update_counter` method, but there's no `increment_counter` method, just check out what's happening with this `increment_counter` method in your Like, Post and Comment models.


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Yorsyboy** [comment]
Thanks for all suggestion , will fix it in my next PR

**Comment by smunozmo** [comment]
@Yorsyboy sure! Happy coding 🤘 🤓

**Pull request merged**
